### ISSUE TITLE
Getting pipeline working with Weixin's original code: todos 

### ISSUE THREAD

**Issue by RemyMess** [RemyMess/MMVRC_ICCV_2021_Skeleton_based_Action_Recognition#3]
- [x] Get datagrabber to work (./src/data_grabber.py working with raw data populated in raw_data)
- [x] Get original pre normaliser code to work (./src/preprocessing/pre_normaliser.py)
- [x] Get augmented siganture transform code to work (./src/augmented_sig_transformer.py)
- [x] Get classifier to work (./src/algos/sig_classfier.py)
- [x] Run main.py and see if learning metrics are meaningful

For all tasks, follow original code in ".base_notebook"

**Comment by erapsch** [comment]
I'll try today afternoon and tomorrow.

**Comment by erapsch** [comment]
The pipeline is now online in the branches "pipeline" and "master". I have debugged it and it worked so far.
Note that: 
1. The pre_normaliser.py is the pipeline-version from Friday morning. Formally it is functional. However, the contents have to be adapted, namely Weixin's, Hannes' and the original uav per normalisers have to be compared and they should be integrated into the pre_normaliser.py script above. Hannes and I discussed this today morning (problems, for instance: switch bodies, centering, rotating, eliminating spikes, eliminate [or understand seemingly] incomprehensibl samples).
2. Other algos can be added in the algos folder in form of a .py script defining a class. Then, it should be integrated in __init__ in main.py just as I did with "SigClassifier", using the alternative (if... elif ...). Your method may contain saving of prenormalised data, it can use different prenormalisation steps etc.. But please use the same preNormalisation class, and extend its attributes / methods if necessary. This is important in order to keep everybody in the project on the same page.
